package:
  name: "openhexa.sdk"
  version: {{ VERSION }}

source:
  path: ..

build:
  script_env:
   - VERSION
  entry_points:
    - openhexa = openhexa.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
requirements:
  host:
    - python >=3.11,<3.15
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.11,<3.15
    - urllib3<2
    - multiprocess>=0.70.15,<0.71.dev0
    - requests>=2.31
    - pyyaml
    - click>=8.1.3,<8.2.dev0
    - jinja2>3,<4
    - docker-py

test:
  imports:
    - openhexa.sdk
  commands:
    - openhexa --help
    - pip check
  requires:
    - pip

about:
  summary: OpenHEXA SDK
  home: https://github.com/blsq/openhexa-sdk-python
  license: 'MIT'
  license_file: LICENCE

extra:
  recipe-maintainers:
    - qgerome
