repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.8
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format

- repo: local
  hooks:
    - id: gqlg
      name: gqlg
      entry: bash -c
        echo "Running gqlg" && \
        gqlg --schemaFilePath ./openhexa/cli/graphql/schema.generated.graphql --destDirPath ./openhexa/cli/graphql/queries/gqlg --depthLimit 3
      language: system
      types: [ graphql ]
      pass_filenames: false
    - id: ariadne-codegen
      name: ariadne-codegen
      entry: bash -c
        echo "Running ariadne-codegen" && \
        ariadne-codegen
      language: system
      types: [graphql]
      pass_filenames: false