repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.8
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format

- repo: local
  hooks:
    - id: ariadne-codegen
      name: ariadne-codegen
      entry: ariadne-codegen
      language: python
      types: [graphql]
      pass_filenames: false