# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel
from .enums import AccessmodAccessRequestStatus


class AccessmodAccessRequests(BaseModel):
    accessmod_access_requests: "AccessmodAccessRequestsAccessmodAccessRequests" = Field(
        alias="accessmodAccessRequests"
    )


class AccessmodAccessRequestsAccessmodAccessRequests(BaseModel):
    items: List["AccessmodAccessRequestsAccessmodAccessRequestsItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class AccessmodAccessRequestsAccessmodAccessRequestsItems(BaseModel):
    accepted_tos: bool = Field(alias="acceptedTos")
    created_at: Any = Field(alias="createdAt")
    email: str
    first_name: str = Field(alias="firstName")
    id: str
    last_name: str = Field(alias="lastName")
    status: AccessmodAccessRequestStatus
    updated_at: Any = Field(alias="updatedAt")


AccessmodAccessRequests.model_rebuild()
AccessmodAccessRequestsAccessmodAccessRequests.model_rebuild()
