# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AccessmodFilesetFormat,
    AccessmodFilesetMode,
    AccessmodFilesetRoleCode,
    AccessmodFilesetStatus,
)


class AccessmodFilesets(BaseModel):
    accessmod_filesets: "AccessmodFilesetsAccessmodFilesets" = Field(
        alias="accessmodFilesets"
    )


class AccessmodFilesetsAccessmodFilesets(BaseModel):
    items: List["AccessmodFilesetsAccessmodFilesetsItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class AccessmodFilesetsAccessmodFilesetsItems(BaseModel):
    author: "AccessmodFilesetsAccessmodFilesetsItemsAuthor"
    created_at: Any = Field(alias="createdAt")
    files: List["AccessmodFilesetsAccessmodFilesetsItemsFiles"]
    id: str
    metadata: Any
    mode: AccessmodFilesetMode
    name: str
    owner: Optional[
        Annotated[
            Union[
                "AccessmodFilesetsAccessmodFilesetsItemsOwnerTeam",
                "AccessmodFilesetsAccessmodFilesetsItemsOwnerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    permissions: "AccessmodFilesetsAccessmodFilesetsItemsPermissions"
    role: "AccessmodFilesetsAccessmodFilesetsItemsRole"
    status: AccessmodFilesetStatus
    updated_at: Any = Field(alias="updatedAt")


class AccessmodFilesetsAccessmodFilesetsItemsAuthor(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class AccessmodFilesetsAccessmodFilesetsItemsFiles(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: str
    mime_type: str = Field(alias="mimeType")
    name: str
    updated_at: Any = Field(alias="updatedAt")
    uri: str


class AccessmodFilesetsAccessmodFilesetsItemsOwnerTeam(BaseModel):
    typename__: Literal["Team"] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    id: Any
    memberships: "AccessmodFilesetsAccessmodFilesetsItemsOwnerTeamMemberships"
    name: str
    permissions: "AccessmodFilesetsAccessmodFilesetsItemsOwnerTeamPermissions"
    updated_at: Any = Field(alias="updatedAt")


class AccessmodFilesetsAccessmodFilesetsItemsOwnerTeamMemberships(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class AccessmodFilesetsAccessmodFilesetsItemsOwnerTeamPermissions(BaseModel):
    create_membership: bool = Field(alias="createMembership")
    delete: bool
    update: bool


class AccessmodFilesetsAccessmodFilesetsItemsOwnerUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    avatar: "AccessmodFilesetsAccessmodFilesetsItemsOwnerUserAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class AccessmodFilesetsAccessmodFilesetsItemsOwnerUserAvatar(BaseModel):
    color: str
    initials: str


class AccessmodFilesetsAccessmodFilesetsItemsPermissions(BaseModel):
    create_file: bool = Field(alias="createFile")
    delete: bool
    update: bool


class AccessmodFilesetsAccessmodFilesetsItemsRole(BaseModel):
    code: AccessmodFilesetRoleCode
    created_at: Any = Field(alias="createdAt")
    format: AccessmodFilesetFormat
    id: str
    name: str
    updated_at: Any = Field(alias="updatedAt")


AccessmodFilesets.model_rebuild()
AccessmodFilesetsAccessmodFilesets.model_rebuild()
AccessmodFilesetsAccessmodFilesetsItems.model_rebuild()
AccessmodFilesetsAccessmodFilesetsItemsOwnerTeam.model_rebuild()
AccessmodFilesetsAccessmodFilesetsItemsOwnerUser.model_rebuild()
