# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel
from .enums import AccessmodFilesetFormat, AccessmodFilesetRoleCode


class AccessmodFilesetRoles(BaseModel):
    accessmod_fileset_roles: List["AccessmodFilesetRolesAccessmodFilesetRoles"] = Field(
        alias="accessmodFilesetRoles"
    )


class AccessmodFilesetRolesAccessmodFilesetRoles(BaseModel):
    code: AccessmodFilesetRoleCode
    created_at: Any = Field(alias="createdAt")
    format: AccessmodFilesetFormat
    id: str
    name: str
    updated_at: Any = Field(alias="updatedAt")


AccessmodFilesetRoles.model_rebuild()
