# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AccessmodFilesetFormat, AccessmodFilesetRoleCode


class AccessmodFilesetRole(BaseModel):
    accessmod_fileset_role: Optional["AccessmodFilesetRoleAccessmodFilesetRole"] = (
        Field(alias="accessmodFilesetRole")
    )


class AccessmodFilesetRoleAccessmodFilesetRole(BaseModel):
    code: AccessmodFilesetRoleCode
    created_at: Any = Field(alias="createdAt")
    format: AccessmodFilesetFormat
    id: str
    name: str
    updated_at: Any = Field(alias="updatedAt")


AccessmodFilesetRole.model_rebuild()
