# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import AddToFavoritesError


class AddToFavorites(BaseModel):
    add_to_favorites: "AddToFavoritesAddToFavorites" = Field(alias="addToFavorites")


class AddToFavoritesAddToFavorites(BaseModel):
    errors: List[AddToFavoritesError]
    success: bool


AddToFavorites.model_rebuild()
