# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import ApproveAccessmodAccessRequestError


class ApproveAccessmodAccessRequest(BaseModel):
    approve_accessmod_access_request: (
        "ApproveAccessmodAccessRequestApproveAccessmodAccessRequest"
    ) = Field(alias="approveAccessmodAccessRequest")


class ApproveAccessmodAccessRequestApproveAccessmodAccessRequest(BaseModel):
    errors: List[ApproveAccessmodAccessRequestError]
    success: bool


ApproveAccessmodAccessRequest.model_rebuild()
