# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import ArchiveWorkspaceError


class ArchiveWorkspace(BaseModel):
    archive_workspace: "ArchiveWorkspaceArchiveWorkspace" = Field(
        alias="archiveWorkspace"
    )


class ArchiveWorkspaceArchiveWorkspace(BaseModel):
    errors: List[ArchiveWorkspaceError]
    success: bool


ArchiveWorkspace.model_rebuild()
