# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class Boundaries(BaseModel):
    boundaries: List["BoundariesBoundaries"]


class BoundariesBoundaries(BaseModel):
    administrative_level: int
    country: "BoundariesBoundariesCountry"
    extent: str
    id: str
    name: str
    parent: Optional[str]


class BoundariesBoundariesCountry(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str
    who_info: "BoundariesBoundariesCountryWhoInfo" = Field(alias="whoInfo")


class BoundariesBoundariesCountryWhoInfo(BaseModel):
    default_crs: int = Field(alias="defaultCRS")
    simplified_extent: Optional[Any] = Field(alias="simplifiedExtent")


Boundaries.model_rebuild()
BoundariesBoundaries.model_rebuild()
BoundariesBoundariesCountry.model_rebuild()
