# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class Config(BaseModel):
    config: "ConfigConfig"


class ConfigConfig(BaseModel):
    password_requirements: Optional[List[str]] = Field(alias="passwordRequirements")


Config.model_rebuild()
