# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ConnectionType


class Connection(BaseModel):
    connection: Optional["ConnectionConnection"]


class ConnectionConnection(BaseModel):
    typename__: Literal[
        "Connection",
        "CustomConnection",
        "DHIS2Connection",
        "GCSConnection",
        "IASOConnection",
        "PostgreSQLConnection",
        "S3Connection",
    ] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    fields: List["ConnectionConnectionFields"]
    id: str
    name: str
    permissions: "ConnectionConnectionPermissions"
    slug: str
    type: ConnectionType
    updated_at: Optional[Any] = Field(alias="updatedAt")
    user: Optional["ConnectionConnectionUser"]


class ConnectionConnectionFields(BaseModel):
    code: str
    created_at: Any = Field(alias="createdAt")
    secret: bool
    updated_at: Optional[Any] = Field(alias="updatedAt")
    value: Optional[str]


class ConnectionConnectionPermissions(BaseModel):
    delete: bool
    update: bool


class ConnectionConnectionUser(BaseModel):
    avatar: "ConnectionConnectionUserAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class ConnectionConnectionUserAvatar(BaseModel):
    color: str
    initials: str


Connection.model_rebuild()
ConnectionConnection.model_rebuild()
ConnectionConnectionUser.model_rebuild()
