# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class Countries(BaseModel):
    countries: List["CountriesCountries"]


class CountriesCountries(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str
    who_info: "CountriesCountriesWhoInfo" = Field(alias="whoInfo")


class CountriesCountriesWhoInfo(BaseModel):
    default_crs: int = Field(alias="defaultCRS")
    region: Optional["CountriesCountriesWhoInfoRegion"]
    simplified_extent: Optional[Any] = Field(alias="simplifiedExtent")


class CountriesCountriesWhoInfoRegion(BaseModel):
    code: str
    name: str


Countries.model_rebuild()
CountriesCountries.model_rebuild()
CountriesCountriesWhoInfo.model_rebuild()
