# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class Country(BaseModel):
    country: Optional["CountryCountry"]


class CountryCountry(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str
    who_info: "CountryCountryWhoInfo" = Field(alias="whoInfo")


class CountryCountryWhoInfo(BaseModel):
    default_crs: int = Field(alias="defaultCRS")
    region: Optional["CountryCountryWhoInfoRegion"]
    simplified_extent: Optional[Any] = Field(alias="simplifiedExtent")


class CountryCountryWhoInfoRegion(BaseModel):
    code: str
    name: str


Country.model_rebuild()
CountryCountry.model_rebuild()
CountryCountryWhoInfo.model_rebuild()
