# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineError, PipelineNotificationLevel, PipelineType


class CreatePipeline(BaseModel):
    create_pipeline: "CreatePipelineCreatePipeline" = Field(alias="createPipeline")


class CreatePipelineCreatePipeline(BaseModel):
    errors: List[PipelineError]
    pipeline: Optional["CreatePipelineCreatePipelinePipeline"]
    success: bool


class CreatePipelineCreatePipelinePipeline(BaseModel):
    code: str
    config: Any
    created_at: Any = Field(alias="createdAt")
    current_version: Optional["CreatePipelineCreatePipelinePipelineCurrentVersion"] = (
        Field(alias="currentVersion")
    )
    description: Optional[str]
    has_new_template_versions: bool = Field(alias="hasNewTemplateVersions")
    id: Any
    name: Optional[str]
    new_template_versions: List[
        "CreatePipelineCreatePipelinePipelineNewTemplateVersions"
    ] = Field(alias="newTemplateVersions")
    notebook_path: Optional[str] = Field(alias="notebookPath")
    permissions: "CreatePipelineCreatePipelinePipelinePermissions"
    recipients: List["CreatePipelineCreatePipelinePipelineRecipients"]
    runs: "CreatePipelineCreatePipelinePipelineRuns"
    schedule: Optional[str]
    source_template: Optional["CreatePipelineCreatePipelinePipelineSourceTemplate"] = (
        Field(alias="sourceTemplate")
    )
    template: Optional["CreatePipelineCreatePipelinePipelineTemplate"]
    type: PipelineType
    updated_at: Optional[Any] = Field(alias="updatedAt")
    versions: "CreatePipelineCreatePipelinePipelineVersions"
    webhook_enabled: bool = Field(alias="webhookEnabled")
    webhook_url: Optional[str] = Field(alias="webhookUrl")
    workspace: "CreatePipelineCreatePipelinePipelineWorkspace"


class CreatePipelineCreatePipelinePipelineCurrentVersion(BaseModel):
    config: Optional[Any]
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    external_link: Optional[Any] = Field(alias="externalLink")
    id: Any
    is_latest_version: bool = Field(alias="isLatestVersion")
    name: Optional[str]
    timeout: Optional[int]
    version_name: str = Field(alias="versionName")
    version_number: int = Field(alias="versionNumber")
    zipfile: str


class CreatePipelineCreatePipelinePipelineNewTemplateVersions(BaseModel):
    changelog: Optional[str]
    created_at: Any = Field(alias="createdAt")
    id: Any
    is_latest_version: bool = Field(alias="isLatestVersion")
    version_number: int = Field(alias="versionNumber")


class CreatePipelineCreatePipelinePipelinePermissions(BaseModel):
    create_version: bool = Field(alias="createVersion")
    delete: bool
    run: bool
    schedule: bool
    stop_pipeline: bool = Field(alias="stopPipeline")
    update: bool


class CreatePipelineCreatePipelinePipelineRecipients(BaseModel):
    id: Any
    notification_level: PipelineNotificationLevel = Field(alias="notificationLevel")


class CreatePipelineCreatePipelinePipelineRuns(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class CreatePipelineCreatePipelinePipelineSourceTemplate(BaseModel):
    code: str
    config: Optional[str]
    description: Optional[str]
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class CreatePipelineCreatePipelinePipelineTemplate(BaseModel):
    code: str
    config: Optional[str]
    description: Optional[str]
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class CreatePipelineCreatePipelinePipelineVersions(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class CreatePipelineCreatePipelinePipelineWorkspace(BaseModel):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


CreatePipeline.model_rebuild()
CreatePipelineCreatePipeline.model_rebuild()
CreatePipelineCreatePipelinePipeline.model_rebuild()
