# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BucketObjectType, CreateBucketFolderError


class CreateBucketFolder(BaseModel):
    create_bucket_folder: "CreateBucketFolderCreateBucketFolder" = Field(
        alias="createBucketFolder"
    )


class CreateBucketFolderCreateBucketFolder(BaseModel):
    errors: List[CreateBucketFolderError]
    folder: Optional["CreateBucketFolderCreateBucketFolderFolder"]
    success: bool


class CreateBucketFolderCreateBucketFolderFolder(BaseModel):
    key: str
    name: str
    path: str
    size: Optional[Any]
    type: BucketObjectType
    updated_at: Optional[Any] = Field(alias="updatedAt")


CreateBucketFolder.model_rebuild()
CreateBucketFolderCreateBucketFolder.model_rebuild()
