# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AccessmodFilesetMode,
    AccessmodFilesetStatus,
    CreateAccessmodProjectError,
    PermissionMode,
)


class CreateAccessmodProject(BaseModel):
    create_accessmod_project: "CreateAccessmodProjectCreateAccessmodProject" = Field(
        alias="createAccessmodProject"
    )


class CreateAccessmodProjectCreateAccessmodProject(BaseModel):
    errors: List[CreateAccessmodProjectError]
    project: Optional["CreateAccessmodProjectCreateAccessmodProjectProject"]
    success: bool


class CreateAccessmodProjectCreateAccessmodProjectProject(BaseModel):
    author: "CreateAccessmodProjectCreateAccessmodProjectProjectAuthor"
    country: "CreateAccessmodProjectCreateAccessmodProjectProjectCountry"
    created_at: Any = Field(alias="createdAt")
    crs: int
    dem: Optional["CreateAccessmodProjectCreateAccessmodProjectProjectDem"]
    description: str
    extent: Optional[List[List[float]]]
    id: str
    members: List["CreateAccessmodProjectCreateAccessmodProjectProjectMembers"]
    name: str
    owner: Optional[
        Annotated[
            Union[
                "CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeam",
                "CreateAccessmodProjectCreateAccessmodProjectProjectOwnerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    permissions: "CreateAccessmodProjectCreateAccessmodProjectProjectPermissions"
    spatial_resolution: int = Field(alias="spatialResolution")
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodProjectCreateAccessmodProjectProjectAuthor(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class CreateAccessmodProjectCreateAccessmodProjectProjectCountry(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str


class CreateAccessmodProjectCreateAccessmodProjectProjectDem(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: str
    metadata: Any
    mode: AccessmodFilesetMode
    name: str
    owner: Optional[
        Annotated[
            Union[
                "CreateAccessmodProjectCreateAccessmodProjectProjectDemOwnerTeam",
                "CreateAccessmodProjectCreateAccessmodProjectProjectDemOwnerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    status: AccessmodFilesetStatus
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodProjectCreateAccessmodProjectProjectDemOwnerTeam(BaseModel):
    typename__: Literal["Team"] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodProjectCreateAccessmodProjectProjectDemOwnerUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class CreateAccessmodProjectCreateAccessmodProjectProjectMembers(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: str
    mode: PermissionMode
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeam(BaseModel):
    typename__: Literal["Team"] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    id: Any
    memberships: (
        "CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeamMemberships"
    )
    name: str
    permissions: (
        "CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeamPermissions"
    )
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeamMemberships(
    BaseModel
):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeamPermissions(
    BaseModel
):
    create_membership: bool = Field(alias="createMembership")
    delete: bool
    update: bool


class CreateAccessmodProjectCreateAccessmodProjectProjectOwnerUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    avatar: "CreateAccessmodProjectCreateAccessmodProjectProjectOwnerUserAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class CreateAccessmodProjectCreateAccessmodProjectProjectOwnerUserAvatar(BaseModel):
    color: str
    initials: str


class CreateAccessmodProjectCreateAccessmodProjectProjectPermissions(BaseModel):
    create_analysis: bool = Field(alias="createAnalysis")
    create_fileset: bool = Field(alias="createFileset")
    create_member: bool = Field(alias="createMember")
    create_permission: bool = Field(alias="createPermission")
    delete: bool
    update: bool


CreateAccessmodProject.model_rebuild()
CreateAccessmodProjectCreateAccessmodProject.model_rebuild()
CreateAccessmodProjectCreateAccessmodProjectProject.model_rebuild()
CreateAccessmodProjectCreateAccessmodProjectProjectDem.model_rebuild()
CreateAccessmodProjectCreateAccessmodProjectProjectOwnerTeam.model_rebuild()
CreateAccessmodProjectCreateAccessmodProjectProjectOwnerUser.model_rebuild()
