# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AccessmodFilesetFormat,
    AccessmodFilesetMode,
    AccessmodFilesetRoleCode,
    AccessmodFilesetStatus,
    CreateAccessmodFilesetError,
)


class CreateAccessmodFileset(BaseModel):
    create_accessmod_fileset: "CreateAccessmodFilesetCreateAccessmodFileset" = Field(
        alias="createAccessmodFileset"
    )


class CreateAccessmodFilesetCreateAccessmodFileset(BaseModel):
    errors: List[CreateAccessmodFilesetError]
    fileset: Optional["CreateAccessmodFilesetCreateAccessmodFilesetFileset"]
    success: bool


class CreateAccessmodFilesetCreateAccessmodFilesetFileset(BaseModel):
    author: "CreateAccessmodFilesetCreateAccessmodFilesetFilesetAuthor"
    created_at: Any = Field(alias="createdAt")
    files: List["CreateAccessmodFilesetCreateAccessmodFilesetFilesetFiles"]
    id: str
    metadata: Any
    mode: AccessmodFilesetMode
    name: str
    owner: Optional[
        Annotated[
            Union[
                "CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeam",
                "CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    permissions: "CreateAccessmodFilesetCreateAccessmodFilesetFilesetPermissions"
    role: "CreateAccessmodFilesetCreateAccessmodFilesetFilesetRole"
    status: AccessmodFilesetStatus
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetAuthor(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetFiles(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: str
    mime_type: str = Field(alias="mimeType")
    name: str
    updated_at: Any = Field(alias="updatedAt")
    uri: str


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeam(BaseModel):
    typename__: Literal["Team"] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    id: Any
    memberships: (
        "CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeamMemberships"
    )
    name: str
    permissions: (
        "CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeamPermissions"
    )
    updated_at: Any = Field(alias="updatedAt")


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeamMemberships(
    BaseModel
):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeamPermissions(
    BaseModel
):
    create_membership: bool = Field(alias="createMembership")
    delete: bool
    update: bool


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    avatar: "CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerUserAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerUserAvatar(BaseModel):
    color: str
    initials: str


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetPermissions(BaseModel):
    create_file: bool = Field(alias="createFile")
    delete: bool
    update: bool


class CreateAccessmodFilesetCreateAccessmodFilesetFilesetRole(BaseModel):
    code: AccessmodFilesetRoleCode
    created_at: Any = Field(alias="createdAt")
    format: AccessmodFilesetFormat
    id: str
    name: str
    updated_at: Any = Field(alias="updatedAt")


CreateAccessmodFileset.model_rebuild()
CreateAccessmodFilesetCreateAccessmodFileset.model_rebuild()
CreateAccessmodFilesetCreateAccessmodFilesetFileset.model_rebuild()
CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerTeam.model_rebuild()
CreateAccessmodFilesetCreateAccessmodFilesetFilesetOwnerUser.model_rebuild()
