# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    DeclineWorkspaceInvitationError,
    WorkspaceInvitationStatus,
    WorkspaceMembershipRole,
)


class DeclineWorkspaceInvitation(BaseModel):
    decline_workspace_invitation: (
        "DeclineWorkspaceInvitationDeclineWorkspaceInvitation"
    ) = Field(alias="declineWorkspaceInvitation")


class DeclineWorkspaceInvitationDeclineWorkspaceInvitation(BaseModel):
    errors: List[DeclineWorkspaceInvitationError]
    invitation: Optional[
        "DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitation"
    ]
    success: bool


class DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitation(BaseModel):
    created_at: Any = Field(alias="createdAt")
    email: str
    id: Any
    invited_by: Optional[
        "DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitationInvitedBy"
    ] = Field(alias="invitedBy")
    role: WorkspaceMembershipRole
    status: WorkspaceInvitationStatus
    updated_at: Optional[Any] = Field(alias="updatedAt")
    workspace: "DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitationWorkspace"


class DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitationInvitedBy(
    BaseModel
):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitationWorkspace(
    BaseModel
):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


DeclineWorkspaceInvitation.model_rebuild()
DeclineWorkspaceInvitationDeclineWorkspaceInvitation.model_rebuild()
DeclineWorkspaceInvitationDeclineWorkspaceInvitationInvitation.model_rebuild()
