# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineRecipientError


class DeletePipelineRecipient(BaseModel):
    delete_pipeline_recipient: "DeletePipelineRecipientDeletePipelineRecipient" = Field(
        alias="deletePipelineRecipient"
    )


class DeletePipelineRecipientDeletePipelineRecipient(BaseModel):
    errors: List[PipelineRecipientError]
    success: bool


DeletePipelineRecipient.model_rebuild()
