# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteWorkspaceInvitationError


class DeleteWorkspaceInvitation(BaseModel):
    delete_workspace_invitation: (
        "DeleteWorkspaceInvitationDeleteWorkspaceInvitation"
    ) = Field(alias="deleteWorkspaceInvitation")


class DeleteWorkspaceInvitationDeleteWorkspaceInvitation(BaseModel):
    errors: List[DeleteWorkspaceInvitationError]
    success: bool


DeleteWorkspaceInvitation.model_rebuild()
