# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteMembershipError


class DeleteMembership(BaseModel):
    delete_membership: "DeleteMembershipDeleteMembership" = Field(
        alias="deleteMembership"
    )


class DeleteMembershipDeleteMembership(BaseModel):
    errors: List[DeleteMembershipError]
    success: bool


DeleteMembership.model_rebuild()
