# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteWebappError


class DeleteWebapp(BaseModel):
    delete_webapp: "DeleteWebappDeleteWebapp" = Field(alias="deleteWebapp")


class DeleteWebappDeleteWebapp(BaseModel):
    errors: List[DeleteWebappError]
    success: bool


DeleteWebapp.model_rebuild()
