# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteTeamError


class DeleteTeam(BaseModel):
    delete_team: "DeleteTeamDeleteTeam" = Field(alias="deleteTeam")


class DeleteTeamDeleteTeam(BaseModel):
    errors: List[DeleteTeamError]
    success: bool


DeleteTeam.model_rebuild()
