# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteAccessmodProjectError


class DeleteAccessmodProject(BaseModel):
    delete_accessmod_project: "DeleteAccessmodProjectDeleteAccessmodProject" = Field(
        alias="deleteAccessmodProject"
    )


class DeleteAccessmodProjectDeleteAccessmodProject(BaseModel):
    errors: List[DeleteAccessmodProjectError]
    success: bool


DeleteAccessmodProject.model_rebuild()
