# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineTemplateError


class DeletePipelineTemplate(BaseModel):
    delete_pipeline_template: "DeletePipelineTemplateDeletePipelineTemplate" = Field(
        alias="deletePipelineTemplate"
    )


class DeletePipelineTemplateDeletePipelineTemplate(BaseModel):
    errors: List[PipelineTemplateError]
    success: bool


DeletePipelineTemplate.model_rebuild()
