# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteAccessmodAnalysisError


class DeleteAccessmodAnalysis(BaseModel):
    delete_accessmod_analysis: "DeleteAccessmodAnalysisDeleteAccessmodAnalysis" = Field(
        alias="deleteAccessmodAnalysis"
    )


class DeleteAccessmodAnalysisDeleteAccessmodAnalysis(BaseModel):
    errors: List[DeleteAccessmodAnalysisError]
    success: bool


DeleteAccessmodAnalysis.model_rebuild()
