# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeletePipelineVersionError


class DeletePipelineVersion(BaseModel):
    delete_pipeline_version: "DeletePipelineVersionDeletePipelineVersion" = Field(
        alias="deletePipelineVersion"
    )


class DeletePipelineVersionDeletePipelineVersion(BaseModel):
    errors: List[DeletePipelineVersionError]
    success: bool


DeletePipelineVersion.model_rebuild()
