# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteWorkspaceMemberError


class DeleteWorkspaceMember(BaseModel):
    delete_workspace_member: "DeleteWorkspaceMemberDeleteWorkspaceMember" = Field(
        alias="deleteWorkspaceMember"
    )


class DeleteWorkspaceMemberDeleteWorkspaceMember(BaseModel):
    errors: List[DeleteWorkspaceMemberError]
    success: bool


DeleteWorkspaceMember.model_rebuild()
