# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineError


class DeletePipeline(BaseModel):
    delete_pipeline: "DeletePipelineDeletePipeline" = Field(alias="deletePipeline")


class DeletePipelineDeletePipeline(BaseModel):
    errors: List[PipelineError]
    success: bool


DeletePipeline.model_rebuild()
