# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteTemplateVersionError


class DeleteTemplateVersion(BaseModel):
    delete_template_version: "DeleteTemplateVersionDeleteTemplateVersion" = Field(
        alias="deleteTemplateVersion"
    )


class DeleteTemplateVersionDeleteTemplateVersion(BaseModel):
    errors: List[DeleteTemplateVersionError]
    success: bool


DeleteTemplateVersion.model_rebuild()
