# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteAccessmodProjectMemberError


class DeleteAccessmodProjectMember(BaseModel):
    delete_accessmod_project_member: (
        "DeleteAccessmodProjectMemberDeleteAccessmodProjectMember"
    ) = Field(alias="deleteAccessmodProjectMember")


class DeleteAccessmodProjectMemberDeleteAccessmodProjectMember(BaseModel):
    errors: List[DeleteAccessmodProjectMemberError]
    success: bool


DeleteAccessmodProjectMember.model_rebuild()
