# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteBucketObjectError


class DeleteBucketObject(BaseModel):
    delete_bucket_object: "DeleteBucketObjectDeleteBucketObject" = Field(
        alias="deleteBucketObject"
    )


class DeleteBucketObjectDeleteBucketObject(BaseModel):
    errors: List[DeleteBucketObjectError]
    success: bool


DeleteBucketObject.model_rebuild()
