# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import DeleteConnectionError


class DeleteConnection(BaseModel):
    delete_connection: "DeleteConnectionDeleteConnection" = Field(
        alias="deleteConnection"
    )


class DeleteConnectionDeleteConnection(BaseModel):
    errors: List[DeleteConnectionError]
    success: bool


DeleteConnection.model_rebuild()
