# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import DisableTwoFactorError


class DisableTwoFactor(BaseModel):
    disable_two_factor: "DisableTwoFactorDisableTwoFactor" = Field(
        alias="disableTwoFactor"
    )


class DisableTwoFactorDisableTwoFactor(BaseModel):
    errors: Optional[List[DisableTwoFactorError]]
    success: bool


DisableTwoFactor.model_rebuild()
