# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from pydantic import Field

from .base_model import BaseModel


class Dummy(BaseModel):
    typename__: str = Field(alias="__typename")
