# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EnableTwoFactorError


class EnableTwoFactor(BaseModel):
    enable_two_factor: "EnableTwoFactorEnableTwoFactor" = Field(alias="enableTwoFactor")


class EnableTwoFactorEnableTwoFactor(BaseModel):
    errors: Optional[List[EnableTwoFactorError]]
    success: bool
    verified: Optional[bool]


EnableTwoFactor.model_rebuild()
