# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import GenerateChallengeError


class GenerateChallenge(BaseModel):
    generate_challenge: "GenerateChallengeGenerateChallenge" = Field(
        alias="generateChallenge"
    )


class GenerateChallengeGenerateChallenge(BaseModel):
    errors: Optional[List[GenerateChallengeError]]
    success: bool


GenerateChallenge.model_rebuild()
