# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import GenerateWorkspaceTokenError


class GenerateWorkspaceToken(BaseModel):
    generate_workspace_token: "GenerateWorkspaceTokenGenerateWorkspaceToken" = Field(
        alias="generateWorkspaceToken"
    )


class GenerateWorkspaceTokenGenerateWorkspaceToken(BaseModel):
    errors: List[GenerateWorkspaceTokenError]
    success: bool
    token: Optional[str]


GenerateWorkspaceToken.model_rebuild()
