# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import InviteWorkspaceMembershipError, WorkspaceMembershipRole


class InviteWorkspaceMember(BaseModel):
    invite_workspace_member: "InviteWorkspaceMemberInviteWorkspaceMember" = Field(
        alias="inviteWorkspaceMember"
    )


class InviteWorkspaceMemberInviteWorkspaceMember(BaseModel):
    errors: List[InviteWorkspaceMembershipError]
    success: bool
    workspace_membership: Optional[
        "InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembership"
    ] = Field(alias="workspaceMembership")


class InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembership(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: Any
    role: WorkspaceMembershipRole
    updated_at: Optional[Any] = Field(alias="updatedAt")
    user: "InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembershipUser"
    workspace: "InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembershipWorkspace"


class InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembershipUser(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembershipWorkspace(BaseModel):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


InviteWorkspaceMember.model_rebuild()
InviteWorkspaceMemberInviteWorkspaceMember.model_rebuild()
InviteWorkspaceMemberInviteWorkspaceMemberWorkspaceMembership.model_rebuild()
