# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ConnectionType,
    JoinWorkspaceError,
    WorkspaceInvitationStatus,
    WorkspaceMembershipRole,
)


class JoinWorkspace(BaseModel):
    join_workspace: "JoinWorkspaceJoinWorkspace" = Field(alias="joinWorkspace")


class JoinWorkspaceJoinWorkspace(BaseModel):
    errors: List[JoinWorkspaceError]
    invitation: Optional["JoinWorkspaceJoinWorkspaceInvitation"]
    success: bool
    workspace: Optional["JoinWorkspaceJoinWorkspaceWorkspace"]


class JoinWorkspaceJoinWorkspaceInvitation(BaseModel):
    created_at: Any = Field(alias="createdAt")
    email: str
    id: Any
    invited_by: Optional["JoinWorkspaceJoinWorkspaceInvitationInvitedBy"] = Field(
        alias="invitedBy"
    )
    role: WorkspaceMembershipRole
    status: WorkspaceInvitationStatus
    updated_at: Optional[Any] = Field(alias="updatedAt")
    workspace: "JoinWorkspaceJoinWorkspaceInvitationWorkspace"


class JoinWorkspaceJoinWorkspaceInvitationInvitedBy(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class JoinWorkspaceJoinWorkspaceInvitationWorkspace(BaseModel):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


class JoinWorkspaceJoinWorkspaceWorkspace(BaseModel):
    bucket: "JoinWorkspaceJoinWorkspaceWorkspaceBucket"
    connections: List["JoinWorkspaceJoinWorkspaceWorkspaceConnections"]
    countries: List["JoinWorkspaceJoinWorkspaceWorkspaceCountries"]
    created_at: Any = Field(alias="createdAt")
    created_by: "JoinWorkspaceJoinWorkspaceWorkspaceCreatedBy" = Field(
        alias="createdBy"
    )
    datasets: "JoinWorkspaceJoinWorkspaceWorkspaceDatasets"
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    invitations: "JoinWorkspaceJoinWorkspaceWorkspaceInvitations"
    members: "JoinWorkspaceJoinWorkspaceWorkspaceMembers"
    name: str
    permissions: "JoinWorkspaceJoinWorkspaceWorkspacePermissions"
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


class JoinWorkspaceJoinWorkspaceWorkspaceBucket(BaseModel):
    name: str


class JoinWorkspaceJoinWorkspaceWorkspaceConnections(BaseModel):
    typename__: Literal[
        "Connection",
        "CustomConnection",
        "DHIS2Connection",
        "GCSConnection",
        "IASOConnection",
        "PostgreSQLConnection",
        "S3Connection",
    ] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    id: str
    name: str
    slug: str
    type: ConnectionType
    updated_at: Optional[Any] = Field(alias="updatedAt")


class JoinWorkspaceJoinWorkspaceWorkspaceCountries(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str


class JoinWorkspaceJoinWorkspaceWorkspaceCreatedBy(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class JoinWorkspaceJoinWorkspaceWorkspaceDatasets(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class JoinWorkspaceJoinWorkspaceWorkspaceInvitations(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class JoinWorkspaceJoinWorkspaceWorkspaceMembers(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class JoinWorkspaceJoinWorkspaceWorkspacePermissions(BaseModel):
    create_connection: bool = Field(alias="createConnection")
    create_dataset: bool = Field(alias="createDataset")
    create_object: bool = Field(alias="createObject")
    create_pipeline: bool = Field(alias="createPipeline")
    create_pipeline_template_version: bool = Field(
        alias="createPipelineTemplateVersion"
    )
    delete: bool
    delete_database_table: bool = Field(alias="deleteDatabaseTable")
    delete_object: bool = Field(alias="deleteObject")
    download_object: bool = Field(alias="downloadObject")
    launch_notebook_server: bool = Field(alias="launchNotebookServer")
    manage_members: bool = Field(alias="manageMembers")
    update: bool


JoinWorkspace.model_rebuild()
JoinWorkspaceJoinWorkspace.model_rebuild()
JoinWorkspaceJoinWorkspaceInvitation.model_rebuild()
JoinWorkspaceJoinWorkspaceWorkspace.model_rebuild()
