# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import LaunchNotebookServerError


class LaunchNotebookServer(BaseModel):
    launch_notebook_server: "LaunchNotebookServerLaunchNotebookServer" = Field(
        alias="launchNotebookServer"
    )


class LaunchNotebookServerLaunchNotebookServer(BaseModel):
    errors: List[LaunchNotebookServerError]
    server: Optional["LaunchNotebookServerLaunchNotebookServerServer"]
    success: bool


class LaunchNotebookServerLaunchNotebookServerServer(BaseModel):
    name: str
    ready: bool
    url: str


LaunchNotebookServer.model_rebuild()
LaunchNotebookServerLaunchNotebookServer.model_rebuild()
