# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineError


class LogPipelineMessage(BaseModel):
    log_pipeline_message: "LogPipelineMessageLogPipelineMessage" = Field(
        alias="logPipelineMessage"
    )


class LogPipelineMessageLogPipelineMessage(BaseModel):
    errors: List[PipelineError]
    success: bool


LogPipelineMessage.model_rebuild()
