# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from .base_model import BaseModel


class Logout(BaseModel):
    logout: "LogoutLogout"


class LogoutLogout(BaseModel):
    success: bool


Logout.model_rebuild()
