# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class MetadataAttributes(BaseModel):
    metadata_attributes: List[Optional["MetadataAttributesMetadataAttributes"]] = Field(
        alias="metadataAttributes"
    )


class MetadataAttributesMetadataAttributes(BaseModel):
    created_at: Any = Field(alias="createdAt")
    created_by: Optional["MetadataAttributesMetadataAttributesCreatedBy"] = Field(
        alias="createdBy"
    )
    id: Any
    key: str
    label: Optional[str]
    system: bool
    updated_at: Any = Field(alias="updatedAt")
    updated_by: Optional["MetadataAttributesMetadataAttributesUpdatedBy"] = Field(
        alias="updatedBy"
    )
    value: Optional[Any]


class MetadataAttributesMetadataAttributesCreatedBy(BaseModel):
    avatar: "MetadataAttributesMetadataAttributesCreatedByAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class MetadataAttributesMetadataAttributesCreatedByAvatar(BaseModel):
    color: str
    initials: str


class MetadataAttributesMetadataAttributesUpdatedBy(BaseModel):
    avatar: "MetadataAttributesMetadataAttributesUpdatedByAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class MetadataAttributesMetadataAttributesUpdatedByAvatar(BaseModel):
    color: str
    initials: str


MetadataAttributes.model_rebuild()
MetadataAttributesMetadataAttributes.model_rebuild()
MetadataAttributesMetadataAttributesCreatedBy.model_rebuild()
MetadataAttributesMetadataAttributesUpdatedBy.model_rebuild()
