# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class NotebooksUrl(BaseModel):
    notebooks_url: Any = Field(alias="notebooksUrl")
