# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel


class Organizations(BaseModel):
    organizations: List["OrganizationsOrganizations"]


class OrganizationsOrganizations(BaseModel):
    contact_info: str = Field(alias="contactInfo")
    id: Any
    name: str
    type: str
    url: str


Organizations.model_rebuild()
