# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import WorkspaceInvitationStatus, WorkspaceMembershipRole


class PendingWorkspaceInvitations(BaseModel):
    pending_workspace_invitations: (
        "PendingWorkspaceInvitationsPendingWorkspaceInvitations"
    ) = Field(alias="pendingWorkspaceInvitations")


class PendingWorkspaceInvitationsPendingWorkspaceInvitations(BaseModel):
    items: List["PendingWorkspaceInvitationsPendingWorkspaceInvitationsItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class PendingWorkspaceInvitationsPendingWorkspaceInvitationsItems(BaseModel):
    created_at: Any = Field(alias="createdAt")
    email: str
    id: Any
    invited_by: Optional[
        "PendingWorkspaceInvitationsPendingWorkspaceInvitationsItemsInvitedBy"
    ] = Field(alias="invitedBy")
    role: WorkspaceMembershipRole
    status: WorkspaceInvitationStatus
    updated_at: Optional[Any] = Field(alias="updatedAt")
    workspace: "PendingWorkspaceInvitationsPendingWorkspaceInvitationsItemsWorkspace"


class PendingWorkspaceInvitationsPendingWorkspaceInvitationsItemsInvitedBy(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class PendingWorkspaceInvitationsPendingWorkspaceInvitationsItemsWorkspace(BaseModel):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


PendingWorkspaceInvitations.model_rebuild()
PendingWorkspaceInvitationsPendingWorkspaceInvitations.model_rebuild()
PendingWorkspaceInvitationsPendingWorkspaceInvitationsItems.model_rebuild()
