# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineError


class PipelineToken(BaseModel):
    pipeline_token: "PipelineTokenPipelineToken" = Field(alias="pipelineToken")


class PipelineTokenPipelineToken(BaseModel):
    errors: List[PipelineError]
    success: bool
    token: Optional[str]


PipelineToken.model_rebuild()
