# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineType


class PipelineTemplates(BaseModel):
    pipeline_templates: "PipelineTemplatesPipelineTemplates" = Field(
        alias="pipelineTemplates"
    )


class PipelineTemplatesPipelineTemplates(BaseModel):
    items: List["PipelineTemplatesPipelineTemplatesItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class PipelineTemplatesPipelineTemplatesItems(BaseModel):
    code: str
    config: Optional[str]
    current_version: Optional[
        "PipelineTemplatesPipelineTemplatesItemsCurrentVersion"
    ] = Field(alias="currentVersion")
    description: Optional[str]
    id: Any
    name: str
    permissions: "PipelineTemplatesPipelineTemplatesItemsPermissions"
    source_pipeline: Optional[
        "PipelineTemplatesPipelineTemplatesItemsSourcePipeline"
    ] = Field(alias="sourcePipeline")
    updated_at: Any = Field(alias="updatedAt")
    versions: "PipelineTemplatesPipelineTemplatesItemsVersions"
    workspace: Optional["PipelineTemplatesPipelineTemplatesItemsWorkspace"]


class PipelineTemplatesPipelineTemplatesItemsCurrentVersion(BaseModel):
    changelog: Optional[str]
    created_at: Any = Field(alias="createdAt")
    id: Any
    is_latest_version: bool = Field(alias="isLatestVersion")
    version_number: int = Field(alias="versionNumber")


class PipelineTemplatesPipelineTemplatesItemsPermissions(BaseModel):
    delete: bool
    update: bool


class PipelineTemplatesPipelineTemplatesItemsSourcePipeline(BaseModel):
    code: str
    config: Any
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    has_new_template_versions: bool = Field(alias="hasNewTemplateVersions")
    id: Any
    name: Optional[str]
    notebook_path: Optional[str] = Field(alias="notebookPath")
    schedule: Optional[str]
    type: PipelineType
    updated_at: Optional[Any] = Field(alias="updatedAt")
    webhook_enabled: bool = Field(alias="webhookEnabled")
    webhook_url: Optional[str] = Field(alias="webhookUrl")


class PipelineTemplatesPipelineTemplatesItemsVersions(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class PipelineTemplatesPipelineTemplatesItemsWorkspace(BaseModel):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


PipelineTemplates.model_rebuild()
PipelineTemplatesPipelineTemplates.model_rebuild()
PipelineTemplatesPipelineTemplatesItems.model_rebuild()
