# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PrepareAccessmodFilesetVisualizationDownload(BaseModel):
    prepare_accessmod_fileset_visualization_download: (
        "PrepareAccessmodFilesetVisualizationDownloadPrepareAccessmodFilesetVisualizationDownload"
    ) = Field(alias="prepareAccessmodFilesetVisualizationDownload")


class PrepareAccessmodFilesetVisualizationDownloadPrepareAccessmodFilesetVisualizationDownload(
    BaseModel
):
    success: bool
    url: Optional[str]


PrepareAccessmodFilesetVisualizationDownload.model_rebuild()
