# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class PrepareDownloadURL(BaseModel):
    prepare_download_url: Optional["PrepareDownloadURLPrepareDownloadUrl"] = Field(
        alias="prepareDownloadURL"
    )


class PrepareDownloadURLPrepareDownloadUrl(BaseModel):
    success: bool
    url: Optional[Any]


PrepareDownloadURL.model_rebuild()
