# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PrepareVersionFileDownloadError


class PrepareVersionFileDownload(BaseModel):
    prepare_version_file_download: (
        "PrepareVersionFileDownloadPrepareVersionFileDownload"
    ) = Field(alias="prepareVersionFileDownload")


class PrepareVersionFileDownloadPrepareVersionFileDownload(BaseModel):
    download_url: Optional[str] = Field(alias="downloadUrl")
    errors: List[PrepareVersionFileDownloadError]
    success: bool


PrepareVersionFileDownload.model_rebuild()
