# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PrepareAccessmodFileUpload(BaseModel):
    prepare_accessmod_file_upload: (
        "PrepareAccessmodFileUploadPrepareAccessmodFileUpload"
    ) = Field(alias="prepareAccessmodFileUpload")


class PrepareAccessmodFileUploadPrepareAccessmodFileUpload(BaseModel):
    file_uri: Optional[str] = Field(alias="fileUri")
    success: bool
    upload_url: Optional[str] = Field(alias="uploadUrl")


PrepareAccessmodFileUpload.model_rebuild()
