# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PrepareObjectDownloadError


class PrepareObjectDownload(BaseModel):
    prepare_object_download: "PrepareObjectDownloadPrepareObjectDownload" = Field(
        alias="prepareObjectDownload"
    )


class PrepareObjectDownloadPrepareObjectDownload(BaseModel):
    download_url: Optional[Any] = Field(alias="downloadUrl")
    errors: List[PrepareObjectDownloadError]
    success: bool


PrepareObjectDownload.model_rebuild()
