# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PrepareAccessmodFileDownload(BaseModel):
    prepare_accessmod_file_download: (
        "PrepareAccessmodFileDownloadPrepareAccessmodFileDownload"
    ) = Field(alias="prepareAccessmodFileDownload")


class PrepareAccessmodFileDownloadPrepareAccessmodFileDownload(BaseModel):
    download_url: Optional[str] = Field(alias="downloadUrl")
    success: bool


PrepareAccessmodFileDownload.model_rebuild()
