# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PrepareObjectUploadError


class PrepareObjectUpload(BaseModel):
    prepare_object_upload: "PrepareObjectUploadPrepareObjectUpload" = Field(
        alias="prepareObjectUpload"
    )


class PrepareObjectUploadPrepareObjectUpload(BaseModel):
    errors: List[PrepareObjectUploadError]
    success: bool
    upload_url: Optional[Any] = Field(alias="uploadUrl")


PrepareObjectUpload.model_rebuild()
