# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List, Optional

from .base_model import BaseModel
from .enums import RegisterError


class Register(BaseModel):
    register: "RegisterRegister"


class RegisterRegister(BaseModel):
    errors: Optional[List[RegisterError]]
    success: bool


Register.model_rebuild()
