# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import RemoveFromFavoritesError


class RemoveFromFavorites(BaseModel):
    remove_from_favorites: "RemoveFromFavoritesRemoveFromFavorites" = Field(
        alias="removeFromFavorites"
    )


class RemoveFromFavoritesRemoveFromFavorites(BaseModel):
    errors: List[RemoveFromFavoritesError]
    success: bool


RemoveFromFavorites.model_rebuild()
