# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import ResendWorkspaceInvitationError


class ResendWorkspaceInvitation(BaseModel):
    resend_workspace_invitation: (
        "ResendWorkspaceInvitationResendWorkspaceInvitation"
    ) = Field(alias="resendWorkspaceInvitation")


class ResendWorkspaceInvitationResendWorkspaceInvitation(BaseModel):
    errors: List[ResendWorkspaceInvitationError]
    success: bool


ResendWorkspaceInvitation.model_rebuild()
