# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import DAGRunStatus, DAGRunTrigger, SetDAGRunFavoriteError


class SetDAGRunFavorite(BaseModel):
    set_dag_run_favorite: Optional["SetDAGRunFavoriteSetDagRunFavorite"] = Field(
        alias="setDAGRunFavorite"
    )


class SetDAGRunFavoriteSetDagRunFavorite(BaseModel):
    dag_run: Optional["SetDAGRunFavoriteSetDagRunFavoriteDagRun"] = Field(
        alias="dagRun"
    )
    errors: List[SetDAGRunFavoriteError]
    success: bool


class SetDAGRunFavoriteSetDagRunFavoriteDagRun(BaseModel):
    config: Optional[Any]
    duration: Optional[int]
    execution_date: Optional[Any] = Field(alias="executionDate")
    external_id: Optional[str] = Field(alias="externalId")
    external_url: Optional[Any] = Field(alias="externalUrl")
    id: Any
    is_favorite: bool = Field(alias="isFavorite")
    label: Optional[str]
    last_refreshed_at: Optional[Any] = Field(alias="lastRefreshedAt")
    logs: Optional[str]
    messages: List["SetDAGRunFavoriteSetDagRunFavoriteDagRunMessages"]
    outputs: List["SetDAGRunFavoriteSetDagRunFavoriteDagRunOutputs"]
    progress: int
    status: DAGRunStatus
    trigger_mode: Optional[DAGRunTrigger] = Field(alias="triggerMode")
    user: Optional["SetDAGRunFavoriteSetDagRunFavoriteDagRunUser"]


class SetDAGRunFavoriteSetDagRunFavoriteDagRunMessages(BaseModel):
    message: str
    priority: str
    timestamp: Optional[Any]


class SetDAGRunFavoriteSetDagRunFavoriteDagRunOutputs(BaseModel):
    title: str
    uri: str


class SetDAGRunFavoriteSetDagRunFavoriteDagRunUser(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


SetDAGRunFavorite.model_rebuild()
SetDAGRunFavoriteSetDagRunFavorite.model_rebuild()
SetDAGRunFavoriteSetDagRunFavoriteDagRun.model_rebuild()
