# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SetPasswordError


class SetPassword(BaseModel):
    set_password: "SetPasswordSetPassword" = Field(alias="setPassword")


class SetPasswordSetPassword(BaseModel):
    error: Optional[SetPasswordError]
    success: bool


SetPassword.model_rebuild()
