# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineError


class StopPipeline(BaseModel):
    stop_pipeline: "StopPipelineStopPipeline" = Field(alias="stopPipeline")


class StopPipelineStopPipeline(BaseModel):
    errors: List[PipelineError]
    success: bool


StopPipeline.model_rebuild()
