# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel


class Teams(BaseModel):
    teams: "TeamsTeams"


class TeamsTeams(BaseModel):
    items: List["TeamsTeamsItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class TeamsTeamsItems(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: Any
    memberships: "TeamsTeamsItemsMemberships"
    name: str
    permissions: "TeamsTeamsItemsPermissions"
    updated_at: Any = Field(alias="updatedAt")


class TeamsTeamsItemsMemberships(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class TeamsTeamsItemsPermissions(BaseModel):
    create_membership: bool = Field(alias="createMembership")
    delete: bool
    update: bool


Teams.model_rebuild()
TeamsTeams.model_rebuild()
TeamsTeamsItems.model_rebuild()
