# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AccessmodFilesetFormat,
    AccessmodFilesetMode,
    AccessmodFilesetRoleCode,
    AccessmodFilesetStatus,
    UpdateAccessmodFilesetError,
)


class UpdateAccessmodFileset(BaseModel):
    update_accessmod_fileset: "UpdateAccessmodFilesetUpdateAccessmodFileset" = Field(
        alias="updateAccessmodFileset"
    )


class UpdateAccessmodFilesetUpdateAccessmodFileset(BaseModel):
    errors: List[UpdateAccessmodFilesetError]
    fileset: Optional["UpdateAccessmodFilesetUpdateAccessmodFilesetFileset"]
    success: bool


class UpdateAccessmodFilesetUpdateAccessmodFilesetFileset(BaseModel):
    author: "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetAuthor"
    created_at: Any = Field(alias="createdAt")
    files: List["UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetFiles"]
    id: str
    metadata: Any
    mode: AccessmodFilesetMode
    name: str
    owner: Optional[
        Annotated[
            Union[
                "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeam",
                "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    permissions: "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetPermissions"
    role: "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetRole"
    status: AccessmodFilesetStatus
    updated_at: Any = Field(alias="updatedAt")


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetAuthor(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetFiles(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: str
    mime_type: str = Field(alias="mimeType")
    name: str
    updated_at: Any = Field(alias="updatedAt")
    uri: str


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeam(BaseModel):
    typename__: Literal["Team"] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    id: Any
    memberships: (
        "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeamMemberships"
    )
    name: str
    permissions: (
        "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeamPermissions"
    )
    updated_at: Any = Field(alias="updatedAt")


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeamMemberships(
    BaseModel
):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeamPermissions(
    BaseModel
):
    create_membership: bool = Field(alias="createMembership")
    delete: bool
    update: bool


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    avatar: "UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerUserAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerUserAvatar(BaseModel):
    color: str
    initials: str


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetPermissions(BaseModel):
    create_file: bool = Field(alias="createFile")
    delete: bool
    update: bool


class UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetRole(BaseModel):
    code: AccessmodFilesetRoleCode
    created_at: Any = Field(alias="createdAt")
    format: AccessmodFilesetFormat
    id: str
    name: str
    updated_at: Any = Field(alias="updatedAt")


UpdateAccessmodFileset.model_rebuild()
UpdateAccessmodFilesetUpdateAccessmodFileset.model_rebuild()
UpdateAccessmodFilesetUpdateAccessmodFilesetFileset.model_rebuild()
UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerTeam.model_rebuild()
UpdateAccessmodFilesetUpdateAccessmodFilesetFilesetOwnerUser.model_rebuild()
