# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import UpdateUserError


class UpdateUser(BaseModel):
    update_user: "UpdateUserUpdateUser" = Field(alias="updateUser")


class UpdateUserUpdateUser(BaseModel):
    errors: List[UpdateUserError]
    success: bool
    user: Optional["UpdateUserUpdateUserUser"]


class UpdateUserUpdateUserUser(BaseModel):
    avatar: "UpdateUserUpdateUserUserAvatar"
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class UpdateUserUpdateUserUserAvatar(BaseModel):
    color: str
    initials: str


UpdateUser.model_rebuild()
UpdateUserUpdateUser.model_rebuild()
UpdateUserUpdateUserUser.model_rebuild()
