# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import PermissionMode, UpdateAccessmodProjectMemberError


class UpdateAccessmodProjectMember(BaseModel):
    update_accessmod_project_member: (
        "UpdateAccessmodProjectMemberUpdateAccessmodProjectMember"
    ) = Field(alias="updateAccessmodProjectMember")


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMember(BaseModel):
    errors: List[UpdateAccessmodProjectMemberError]
    member: Optional["UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMember"]
    success: bool


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMember(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: str
    mode: PermissionMode
    permissions: (
        "UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberPermissions"
    )
    project: "UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProject"
    team: Optional["UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberTeam"]
    updated_at: Any = Field(alias="updatedAt")
    user: Optional["UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberUser"]


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberPermissions(
    BaseModel
):
    delete: bool
    update: bool


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProject(BaseModel):
    created_at: Any = Field(alias="createdAt")
    crs: int
    description: str
    extent: Optional[List[List[float]]]
    id: str
    name: str
    owner: Optional[
        Annotated[
            Union[
                "UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProjectOwnerTeam",
                "UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProjectOwnerUser",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    spatial_resolution: int = Field(alias="spatialResolution")
    updated_at: Any = Field(alias="updatedAt")


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProjectOwnerTeam(
    BaseModel
):
    typename__: Literal["Team"] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProjectOwnerUser(
    BaseModel
):
    typename__: Literal["User"] = Field(alias="__typename")
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberTeam(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberUser(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


UpdateAccessmodProjectMember.model_rebuild()
UpdateAccessmodProjectMemberUpdateAccessmodProjectMember.model_rebuild()
UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMember.model_rebuild()
UpdateAccessmodProjectMemberUpdateAccessmodProjectMemberMemberProject.model_rebuild()
