# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ConnectionType, UpdateWorkspaceError


class UpdateWorkspace(BaseModel):
    update_workspace: "UpdateWorkspaceUpdateWorkspace" = Field(alias="updateWorkspace")


class UpdateWorkspaceUpdateWorkspace(BaseModel):
    errors: List[UpdateWorkspaceError]
    success: bool
    workspace: Optional["UpdateWorkspaceUpdateWorkspaceWorkspace"]


class UpdateWorkspaceUpdateWorkspaceWorkspace(BaseModel):
    bucket: "UpdateWorkspaceUpdateWorkspaceWorkspaceBucket"
    connections: List["UpdateWorkspaceUpdateWorkspaceWorkspaceConnections"]
    countries: List["UpdateWorkspaceUpdateWorkspaceWorkspaceCountries"]
    created_at: Any = Field(alias="createdAt")
    created_by: "UpdateWorkspaceUpdateWorkspaceWorkspaceCreatedBy" = Field(
        alias="createdBy"
    )
    datasets: "UpdateWorkspaceUpdateWorkspaceWorkspaceDatasets"
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    invitations: "UpdateWorkspaceUpdateWorkspaceWorkspaceInvitations"
    members: "UpdateWorkspaceUpdateWorkspaceWorkspaceMembers"
    name: str
    permissions: "UpdateWorkspaceUpdateWorkspaceWorkspacePermissions"
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


class UpdateWorkspaceUpdateWorkspaceWorkspaceBucket(BaseModel):
    name: str


class UpdateWorkspaceUpdateWorkspaceWorkspaceConnections(BaseModel):
    typename__: Literal[
        "Connection",
        "CustomConnection",
        "DHIS2Connection",
        "GCSConnection",
        "IASOConnection",
        "PostgreSQLConnection",
        "S3Connection",
    ] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    id: str
    name: str
    slug: str
    type: ConnectionType
    updated_at: Optional[Any] = Field(alias="updatedAt")


class UpdateWorkspaceUpdateWorkspaceWorkspaceCountries(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str


class UpdateWorkspaceUpdateWorkspaceWorkspaceCreatedBy(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class UpdateWorkspaceUpdateWorkspaceWorkspaceDatasets(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class UpdateWorkspaceUpdateWorkspaceWorkspaceInvitations(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class UpdateWorkspaceUpdateWorkspaceWorkspaceMembers(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class UpdateWorkspaceUpdateWorkspaceWorkspacePermissions(BaseModel):
    create_connection: bool = Field(alias="createConnection")
    create_dataset: bool = Field(alias="createDataset")
    create_object: bool = Field(alias="createObject")
    create_pipeline: bool = Field(alias="createPipeline")
    create_pipeline_template_version: bool = Field(
        alias="createPipelineTemplateVersion"
    )
    delete: bool
    delete_database_table: bool = Field(alias="deleteDatabaseTable")
    delete_object: bool = Field(alias="deleteObject")
    download_object: bool = Field(alias="downloadObject")
    launch_notebook_server: bool = Field(alias="launchNotebookServer")
    manage_members: bool = Field(alias="manageMembers")
    update: bool


UpdateWorkspace.model_rebuild()
UpdateWorkspaceUpdateWorkspace.model_rebuild()
UpdateWorkspaceUpdateWorkspaceWorkspace.model_rebuild()
