# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .enums import PipelineError


class UpdatePipelineProgress(BaseModel):
    update_pipeline_progress: "UpdatePipelineProgressUpdatePipelineProgress" = Field(
        alias="updatePipelineProgress"
    )


class UpdatePipelineProgressUpdatePipelineProgress(BaseModel):
    errors: List[PipelineError]
    success: bool


UpdatePipelineProgress.model_rebuild()
