# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import MembershipRole, UpdateMembershipError


class UpdateMembership(BaseModel):
    update_membership: "UpdateMembershipUpdateMembership" = Field(
        alias="updateMembership"
    )


class UpdateMembershipUpdateMembership(BaseModel):
    errors: List[UpdateMembershipError]
    membership: Optional["UpdateMembershipUpdateMembershipMembership"]
    success: bool


class UpdateMembershipUpdateMembershipMembership(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: Any
    permissions: "UpdateMembershipUpdateMembershipMembershipPermissions"
    role: MembershipRole
    team: "UpdateMembershipUpdateMembershipMembershipTeam"
    updated_at: Any = Field(alias="updatedAt")
    user: "UpdateMembershipUpdateMembershipMembershipUser"


class UpdateMembershipUpdateMembershipMembershipPermissions(BaseModel):
    delete: bool
    update: bool


class UpdateMembershipUpdateMembershipMembershipTeam(BaseModel):
    created_at: Any = Field(alias="createdAt")
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class UpdateMembershipUpdateMembershipMembershipUser(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


UpdateMembership.model_rebuild()
UpdateMembershipUpdateMembership.model_rebuild()
UpdateMembershipUpdateMembershipMembership.model_rebuild()
