# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import UpdateTemplateVersionError


class UpdateTemplateVersion(BaseModel):
    update_template_version: "UpdateTemplateVersionUpdateTemplateVersion" = Field(
        alias="updateTemplateVersion"
    )


class UpdateTemplateVersionUpdateTemplateVersion(BaseModel):
    errors: List[UpdateTemplateVersionError]
    success: bool
    template_version: Optional[
        "UpdateTemplateVersionUpdateTemplateVersionTemplateVersion"
    ] = Field(alias="templateVersion")


class UpdateTemplateVersionUpdateTemplateVersionTemplateVersion(BaseModel):
    changelog: Optional[str]
    created_at: Any = Field(alias="createdAt")
    id: Any
    is_latest_version: bool = Field(alias="isLatestVersion")
    permissions: "UpdateTemplateVersionUpdateTemplateVersionTemplateVersionPermissions"
    template: "UpdateTemplateVersionUpdateTemplateVersionTemplateVersionTemplate"
    user: Optional["UpdateTemplateVersionUpdateTemplateVersionTemplateVersionUser"]
    version_number: int = Field(alias="versionNumber")


class UpdateTemplateVersionUpdateTemplateVersionTemplateVersionPermissions(BaseModel):
    delete: bool
    update: bool


class UpdateTemplateVersionUpdateTemplateVersionTemplateVersionTemplate(BaseModel):
    code: str
    config: Optional[str]
    description: Optional[str]
    id: Any
    name: str
    updated_at: Any = Field(alias="updatedAt")


class UpdateTemplateVersionUpdateTemplateVersionTemplateVersionUser(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


UpdateTemplateVersion.model_rebuild()
UpdateTemplateVersionUpdateTemplateVersion.model_rebuild()
UpdateTemplateVersionUpdateTemplateVersionTemplateVersion.model_rebuild()
