# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ConnectionType, UpdateConnectionError


class UpdateConnection(BaseModel):
    update_connection: "UpdateConnectionUpdateConnection" = Field(
        alias="updateConnection"
    )


class UpdateConnectionUpdateConnection(BaseModel):
    connection: Optional["UpdateConnectionUpdateConnectionConnection"]
    errors: List[UpdateConnectionError]
    success: bool


class UpdateConnectionUpdateConnectionConnection(BaseModel):
    typename__: Literal[
        "Connection",
        "CustomConnection",
        "DHIS2Connection",
        "GCSConnection",
        "IASOConnection",
        "PostgreSQLConnection",
        "S3Connection",
    ] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    fields: List["UpdateConnectionUpdateConnectionConnectionFields"]
    id: str
    name: str
    permissions: "UpdateConnectionUpdateConnectionConnectionPermissions"
    slug: str
    type: ConnectionType
    updated_at: Optional[Any] = Field(alias="updatedAt")
    user: Optional["UpdateConnectionUpdateConnectionConnectionUser"]


class UpdateConnectionUpdateConnectionConnectionFields(BaseModel):
    code: str
    created_at: Any = Field(alias="createdAt")
    secret: bool
    updated_at: Optional[Any] = Field(alias="updatedAt")
    value: Optional[str]


class UpdateConnectionUpdateConnectionConnectionPermissions(BaseModel):
    delete: bool
    update: bool


class UpdateConnectionUpdateConnectionConnectionUser(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


UpdateConnection.model_rebuild()
UpdateConnectionUpdateConnection.model_rebuild()
UpdateConnectionUpdateConnectionConnection.model_rebuild()
