# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class Webapps(BaseModel):
    webapps: "WebappsWebapps"


class WebappsWebapps(BaseModel):
    items: List["WebappsWebappsItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class WebappsWebappsItems(BaseModel):
    created_by: "WebappsWebappsItemsCreatedBy" = Field(alias="createdBy")
    description: Optional[str]
    icon: Optional[str]
    id: Any
    is_favorite: bool = Field(alias="isFavorite")
    name: str
    permissions: "WebappsWebappsItemsPermissions"
    url: str
    workspace: "WebappsWebappsItemsWorkspace"


class WebappsWebappsItemsCreatedBy(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class WebappsWebappsItemsPermissions(BaseModel):
    delete: bool
    update: bool


class WebappsWebappsItemsWorkspace(BaseModel):
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    name: str
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


Webapps.model_rebuild()
WebappsWebapps.model_rebuild()
WebappsWebappsItems.model_rebuild()
