# Generated by ariadne-codegen
# Source: openhexa/cli/graphql/queries

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ConnectionType


class Workspaces(BaseModel):
    workspaces: "WorkspacesWorkspaces"


class WorkspacesWorkspaces(BaseModel):
    items: List["WorkspacesWorkspacesItems"]
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class WorkspacesWorkspacesItems(BaseModel):
    bucket: "WorkspacesWorkspacesItemsBucket"
    connections: List["WorkspacesWorkspacesItemsConnections"]
    countries: List["WorkspacesWorkspacesItemsCountries"]
    created_at: Any = Field(alias="createdAt")
    created_by: "WorkspacesWorkspacesItemsCreatedBy" = Field(alias="createdBy")
    datasets: "WorkspacesWorkspacesItemsDatasets"
    description: Optional[str]
    docker_image: Optional[str] = Field(alias="dockerImage")
    invitations: "WorkspacesWorkspacesItemsInvitations"
    members: "WorkspacesWorkspacesItemsMembers"
    name: str
    permissions: "WorkspacesWorkspacesItemsPermissions"
    slug: str
    updated_at: Optional[Any] = Field(alias="updatedAt")


class WorkspacesWorkspacesItemsBucket(BaseModel):
    name: str


class WorkspacesWorkspacesItemsConnections(BaseModel):
    typename__: Literal[
        "Connection",
        "CustomConnection",
        "DHIS2Connection",
        "GCSConnection",
        "IASOConnection",
        "PostgreSQLConnection",
        "S3Connection",
    ] = Field(alias="__typename")
    created_at: Any = Field(alias="createdAt")
    description: Optional[str]
    id: str
    name: str
    slug: str
    type: ConnectionType
    updated_at: Optional[Any] = Field(alias="updatedAt")


class WorkspacesWorkspacesItemsCountries(BaseModel):
    alpha_3: str = Field(alias="alpha3")
    code: str
    flag: str
    name: str


class WorkspacesWorkspacesItemsCreatedBy(BaseModel):
    date_joined: Any = Field(alias="dateJoined")
    display_name: str = Field(alias="displayName")
    email: str
    first_name: Optional[str] = Field(alias="firstName")
    id: Any
    language: str
    last_login: Optional[Any] = Field(alias="lastLogin")
    last_name: Optional[str] = Field(alias="lastName")


class WorkspacesWorkspacesItemsDatasets(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class WorkspacesWorkspacesItemsInvitations(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class WorkspacesWorkspacesItemsMembers(BaseModel):
    page_number: int = Field(alias="pageNumber")
    total_items: int = Field(alias="totalItems")
    total_pages: int = Field(alias="totalPages")


class WorkspacesWorkspacesItemsPermissions(BaseModel):
    create_connection: bool = Field(alias="createConnection")
    create_dataset: bool = Field(alias="createDataset")
    create_object: bool = Field(alias="createObject")
    create_pipeline: bool = Field(alias="createPipeline")
    create_pipeline_template_version: bool = Field(
        alias="createPipelineTemplateVersion"
    )
    delete: bool
    delete_database_table: bool = Field(alias="deleteDatabaseTable")
    delete_object: bool = Field(alias="deleteObject")
    download_object: bool = Field(alias="downloadObject")
    launch_notebook_server: bool = Field(alias="launchNotebookServer")
    manage_members: bool = Field(alias="manageMembers")
    update: bool


Workspaces.model_rebuild()
WorkspacesWorkspaces.model_rebuild()
WorkspacesWorkspacesItems.model_rebuild()
