query accessmodProject($page: Int, $perPage: Int, $id: String){
    accessmodProject(id: $id){
        author{
            avatar{
                color
                initials
            }
            dateJoined
            displayName
            email
            firstName
            id
            language
            lastLogin
            lastName
        }
        country{
            alpha3
            code
            flag
            name
            whoInfo{
                defaultCRS
                simplifiedExtent
            }
        }
        createdAt
        crs
        dem{
            author{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            createdAt
            files{
                createdAt
                id
                mimeType
                name
                updatedAt
                uri
            }
            id
            metadata
            mode
            name
            owner{
                __typename
                ... on Team {
                    createdAt
                    id
                    memberships(page: $page, perPage: $perPage){
                        pageNumber
                        totalItems
                        totalPages
                    }
                    name
                    permissions{
                        createMembership
                        delete
                        update
                    }
                    updatedAt
                }
                ... on User {
                    avatar{
                        color
                        initials
                    }
                    dateJoined
                    displayName
                    email
                    firstName
                    id
                    language
                    lastLogin
                    lastName
                }
            }
            permissions{
                createFile
                delete
                update
            }
            role{
                code
                createdAt
                format
                id
                name
                updatedAt
            }
            status
            updatedAt
        }
        description
        extent
        id
        members{
            createdAt
            id
            mode
            permissions{
                delete
                update
            }
            project{
                createdAt
                crs
                description
                extent
                id
                name
                owner{
                    __typename
                    ... on Team {
                        createdAt
                        id
                        name
                        updatedAt
                    }
                    ... on User {
                        dateJoined
                        displayName
                        email
                        firstName
                        id
                        language
                        lastLogin
                        lastName
                    }
                }
                spatialResolution
                updatedAt
            }
            team{
                createdAt
                id
                name
                updatedAt
            }
            updatedAt
            user{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
        }
        name
        owner{
            __typename
            ... on Team {
                createdAt
                id
                name
                updatedAt
            }
            ... on User {
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
        }
        permissions{
            createAnalysis
            createFileset
            createMember
            createPermission
            delete
            update
        }
        spatialResolution
        updatedAt
    }
}