query accessmodFileset($page: Int, $perPage: Int, $id: String){
    accessmodFileset(id: $id){
        author{
            avatar{
                color
                initials
            }
            dateJoined
            displayName
            email
            firstName
            id
            language
            lastLogin
            lastName
        }
        createdAt
        files{
            createdAt
            fileset{
                createdAt
                id
                metadata
                mode
                name
                owner{
                    __typename
                    ... on Team {
                        createdAt
                        id
                        name
                        updatedAt
                    }
                    ... on User {
                        dateJoined
                        displayName
                        email
                        firstName
                        id
                        language
                        lastLogin
                        lastName
                    }
                }
                status
                updatedAt
            }
            id
            mimeType
            name
            updatedAt
            uri
        }
        id
        metadata
        mode
        name
        owner{
            __typename
            ... on Team {
                createdAt
                id
                memberships(page: $page, perPage: $perPage){
                    items{
                        createdAt
                        id
                        role
                        updatedAt
                    }
                    pageNumber
                    totalItems
                    totalPages
                }
                name
                permissions{
                    createMembership
                    delete
                    update
                }
                updatedAt
            }
            ... on User {
                avatar{
                    color
                    initials
                }
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
        }
        permissions{
            createFile
            delete
            update
        }
        role{
            code
            createdAt
            format
            id
            name
            updatedAt
        }
        status
        updatedAt
    }
}