query accessmodFilesets($page: Int, $perPage: Int, $mode: AccessmodFilesetMode, $page1: Int, $perPage1: Int, $projectId: String!, $roleId: String, $term: String){
    accessmodFilesets(mode: $mode, page: $page1, perPage: $perPage1, projectId: $projectId, roleId: $roleId, term: $term){
        items{
            author{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            createdAt
            files{
                createdAt
                id
                mimeType
                name
                updatedAt
                uri
            }
            id
            metadata
            mode
            name
            owner{
                __typename
                ... on Team {
                    createdAt
                    id
                    memberships(page: $page, perPage: $perPage){
                        pageNumber
                        totalItems
                        totalPages
                    }
                    name
                    permissions{
                        createMembership
                        delete
                        update
                    }
                    updatedAt
                }
                ... on User {
                    avatar{
                        color
                        initials
                    }
                    dateJoined
                    displayName
                    email
                    firstName
                    id
                    language
                    lastLogin
                    lastName
                }
            }
            permissions{
                createFile
                delete
                update
            }
            role{
                code
                createdAt
                format
                id
                name
                updatedAt
            }
            status
            updatedAt
        }
        pageNumber
        totalItems
        totalPages
    }
}