query dag($orderBy: DAGRunOrderBy, $page: Int, $perPage: Int, $id: UUID!){
    dag(id: $id){
        countries{
            alpha3
            code
            flag
            name
            whoInfo{
                defaultCRS
                simplifiedExtent
            }
        }
        description
        externalId
        externalUrl
        formCode
        id
        label
        runs(orderBy: $orderBy, page: $page, perPage: $perPage){
            items{
                config
                duration
                executionDate
                externalId
                externalUrl
                id
                isFavorite
                label
                lastRefreshedAt
                logs
                progress
                status
                triggerMode
            }
            pageNumber
            totalItems
            totalPages
        }
        schedule
        tags{
            id
            name
        }
        template{
            code
            description
            sampleConfig
        }
        user{
            avatar{
                color
                initials
            }
            dateJoined
            displayName
            email
            firstName
            id
            language
            lastLogin
            lastName
        }
    }
}