query me{
    me{
        features{
            code
        }
        hasTwoFactorEnabled
        permissions{
            adminPanel
            createAccessmodProject
            createTeam
            createWorkspace
            manageAccessmodAccessRequests
            superUser
        }
        user{
            avatar{
                color
                initials
            }
            dateJoined
            displayName
            email
            firstName
            id
            language
            lastLogin
            lastName
        }
    }
}