query pipelineVersion($orderBy: PipelineRunOrderBy, $page: Int, $perPage: Int, $page1: Int, $perPage1: Int, $id: UUID!){
    pipelineVersion(id: $id){
        config
        createdAt
        description
        externalLink
        id
        isLatestVersion
        name
        parameters{
            choices
            code
            connection
            default
            help
            multiple
            name
            required
            type
            widget
        }
        permissions{
            delete
            update
        }
        pipeline{
            code
            config
            createdAt
            currentVersion{
                config
                createdAt
                description
                externalLink
                id
                isLatestVersion
                name
                timeout
                versionName
                versionNumber
                zipfile
            }
            description
            hasNewTemplateVersions
            id
            name
            newTemplateVersions{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            notebookPath
            permissions{
                createVersion
                delete
                run
                schedule
                stopPipeline
                update
            }
            recipients{
                id
                notificationLevel
            }
            runs(orderBy: $orderBy, page: $page, perPage: $perPage){
                pageNumber
                totalItems
                totalPages
            }
            schedule
            sourceTemplate{
                code
                config
                description
                id
                name
                updatedAt
            }
            template{
                code
                config
                description
                id
                name
                updatedAt
            }
            type
            updatedAt
            versions(page: $page1, perPage: $perPage1){
                pageNumber
                totalItems
                totalPages
            }
            webhookEnabled
            webhookUrl
            workspace{
                createdAt
                description
                dockerImage
                name
                slug
                updatedAt
            }
        }
        templateVersion{
            changelog
            createdAt
            id
            isLatestVersion
            permissions{
                delete
                update
            }
            template{
                code
                config
                description
                id
                name
                updatedAt
            }
            user{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            versionNumber
        }
        timeout
        user{
            avatar{
                color
                initials
            }
            dateJoined
            displayName
            email
            firstName
            id
            language
            lastLogin
            lastName
        }
        versionName
        versionNumber
        zipfile
    }
}