query pipelineByCode($orderBy: PipelineRunOrderBy, $page: Int, $perPage: Int, $page1: Int, $perPage1: Int, $page2: Int, $perPage2: Int, $page3: Int, $perPage3: Int, $page4: Int, $perPage4: Int, $pinned: Boolean, $query: String, $includeAccepted: Boolean, $page5: Int, $perPage5: Int, $page6: Int, $perPage6: Int, $code: String!, $workspaceSlug: String!){
    pipelineByCode(code: $code, workspaceSlug: $workspaceSlug){
        code
        config
        createdAt
        currentVersion{
            config
            createdAt
            description
            externalLink
            id
            isLatestVersion
            name
            parameters{
                choices
                code
                connection
                default
                help
                multiple
                name
                required
                type
                widget
            }
            permissions{
                delete
                update
            }
            pipeline{
                code
                config
                createdAt
                description
                hasNewTemplateVersions
                id
                name
                notebookPath
                schedule
                type
                updatedAt
                webhookEnabled
                webhookUrl
            }
            templateVersion{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            timeout
            user{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            versionName
            versionNumber
            zipfile
        }
        description
        hasNewTemplateVersions
        id
        name
        newTemplateVersions{
            changelog
            createdAt
            id
            isLatestVersion
            permissions{
                delete
                update
            }
            template{
                code
                config
                description
                id
                name
                updatedAt
            }
            user{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            versionNumber
        }
        notebookPath
        permissions{
            createTemplateVersion{
                isAllowed
                reasons
            }
            createVersion
            delete
            run
            schedule
            stopPipeline
            update
        }
        recipients{
            id
            notificationLevel
            pipeline{
                code
                config
                createdAt
                description
                hasNewTemplateVersions
                id
                name
                notebookPath
                schedule
                type
                updatedAt
                webhookEnabled
                webhookUrl
            }
            user{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
        }
        runs(orderBy: $orderBy, page: $page, perPage: $perPage){
            items{
                code
                config
                duration
                enableDebugLogs
                executionDate
                id
                logs
                outputs{
                    __typename
                    ... on BucketObject {
                        key
                        name
                        path
                        size
                        type
                        updatedAt
                    }
                    ... on DatabaseTable {
                        count
                        name
                        sample
                    }
                    ... on GenericOutput {
                        genericName
                        genericType
                        genericUri
                    }
                }
                progress
                run_id
                sendMailNotifications
                status
                timeout
                triggerMode
            }
            pageNumber
            totalItems
            totalPages
        }
        schedule
        sourceTemplate{
            code
            config
            currentVersion{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            description
            id
            name
            permissions{
                delete
                update
            }
            sourcePipeline{
                code
                config
                createdAt
                description
                hasNewTemplateVersions
                id
                name
                notebookPath
                schedule
                type
                updatedAt
                webhookEnabled
                webhookUrl
            }
            updatedAt
            versions(page: $page1, perPage: $perPage1){
                pageNumber
                totalItems
                totalPages
            }
            workspace{
                createdAt
                description
                dockerImage
                name
                slug
                updatedAt
            }
        }
        template{
            code
            config
            currentVersion{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            description
            id
            name
            permissions{
                delete
                update
            }
            sourcePipeline{
                code
                config
                createdAt
                description
                hasNewTemplateVersions
                id
                name
                notebookPath
                schedule
                type
                updatedAt
                webhookEnabled
                webhookUrl
            }
            updatedAt
            versions(page: $page2, perPage: $perPage2){
                pageNumber
                totalItems
                totalPages
            }
            workspace{
                createdAt
                description
                dockerImage
                name
                slug
                updatedAt
            }
        }
        type
        updatedAt
        versions(page: $page3, perPage: $perPage3){
            items{
                config
                createdAt
                description
                externalLink
                id
                isLatestVersion
                name
                timeout
                versionName
                versionNumber
                zipfile
            }
            pageNumber
            totalItems
            totalPages
        }
        webhookEnabled
        webhookUrl
        workspace{
            bucket{
                name
            }
            connections{
                createdAt
                description
                id
                name
                slug
                type
                updatedAt
            }
            countries{
                alpha3
                code
                flag
                name
            }
            createdAt
            createdBy{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            datasets(page: $page4, perPage: $perPage4, pinned: $pinned, query: $query){
                pageNumber
                totalItems
                totalPages
            }
            description
            dockerImage
            invitations(includeAccepted: $includeAccepted, page: $page5, perPage: $perPage5){
                pageNumber
                totalItems
                totalPages
            }
            members(page: $page6, perPage: $perPage6){
                pageNumber
                totalItems
                totalPages
            }
            name
            permissions{
                createConnection
                createDataset
                createObject
                createPipeline
                createPipelineTemplateVersion
                delete
                deleteDatabaseTable
                deleteObject
                downloadObject
                launchNotebookServer
                manageMembers
                update
            }
            slug
            updatedAt
        }
    }
}