query pipelines($orderBy: PipelineRunOrderBy, $page: Int, $perPage: Int, $page1: Int, $perPage1: Int, $name: String, $page2: Int, $perPage2: Int, $search: String, $workspaceSlug: String){
    pipelines(name: $name, page: $page2, perPage: $perPage2, search: $search, workspaceSlug: $workspaceSlug){
        items{
            code
            config
            createdAt
            currentVersion{
                config
                createdAt
                description
                externalLink
                id
                isLatestVersion
                name
                timeout
                versionName
                versionNumber
                zipfile
            }
            description
            hasNewTemplateVersions
            id
            name
            newTemplateVersions{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            notebookPath
            permissions{
                createVersion
                delete
                run
                schedule
                stopPipeline
                update
            }
            recipients{
                id
                notificationLevel
            }
            runs(orderBy: $orderBy, page: $page, perPage: $perPage){
                pageNumber
                totalItems
                totalPages
            }
            schedule
            sourceTemplate{
                code
                config
                description
                id
                name
                updatedAt
            }
            template{
                code
                config
                description
                id
                name
                updatedAt
            }
            type
            updatedAt
            versions(page: $page1, perPage: $perPage1){
                pageNumber
                totalItems
                totalPages
            }
            webhookEnabled
            webhookUrl
            workspace{
                createdAt
                description
                dockerImage
                name
                slug
                updatedAt
            }
        }
        pageNumber
        totalItems
        totalPages
    }
}