query templateByCode($orderBy: PipelineRunOrderBy, $page: Int, $perPage: Int, $page1: Int, $perPage1: Int, $page2: Int, $perPage2: Int, $page3: Int, $perPage3: Int, $pinned: Boolean, $query: String, $includeAccepted: Boolean, $page4: Int, $perPage4: Int, $page5: Int, $perPage5: Int, $code: String!){
    templateByCode(code: $code){
        code
        config
        currentVersion{
            changelog
            createdAt
            id
            isLatestVersion
            permissions{
                delete
                update
            }
            template{
                code
                config
                description
                id
                name
                updatedAt
            }
            user{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            versionNumber
        }
        description
        id
        name
        permissions{
            delete
            update
        }
        sourcePipeline{
            code
            config
            createdAt
            currentVersion{
                config
                createdAt
                description
                externalLink
                id
                isLatestVersion
                name
                timeout
                versionName
                versionNumber
                zipfile
            }
            description
            hasNewTemplateVersions
            id
            name
            newTemplateVersions{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            notebookPath
            permissions{
                createVersion
                delete
                run
                schedule
                stopPipeline
                update
            }
            recipients{
                id
                notificationLevel
            }
            runs(orderBy: $orderBy, page: $page, perPage: $perPage){
                pageNumber
                totalItems
                totalPages
            }
            schedule
            sourceTemplate{
                code
                config
                description
                id
                name
                updatedAt
            }
            template{
                code
                config
                description
                id
                name
                updatedAt
            }
            type
            updatedAt
            versions(page: $page1, perPage: $perPage1){
                pageNumber
                totalItems
                totalPages
            }
            webhookEnabled
            webhookUrl
            workspace{
                createdAt
                description
                dockerImage
                name
                slug
                updatedAt
            }
        }
        updatedAt
        versions(page: $page2, perPage: $perPage2){
            items{
                changelog
                createdAt
                id
                isLatestVersion
                versionNumber
            }
            pageNumber
            totalItems
            totalPages
        }
        workspace{
            bucket{
                name
            }
            connections{
                createdAt
                description
                id
                name
                slug
                type
                updatedAt
            }
            countries{
                alpha3
                code
                flag
                name
            }
            createdAt
            createdBy{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            datasets(page: $page3, perPage: $perPage3, pinned: $pinned, query: $query){
                pageNumber
                totalItems
                totalPages
            }
            description
            dockerImage
            invitations(includeAccepted: $includeAccepted, page: $page4, perPage: $perPage4){
                pageNumber
                totalItems
                totalPages
            }
            members(page: $page5, perPage: $perPage5){
                pageNumber
                totalItems
                totalPages
            }
            name
            permissions{
                createConnection
                createDataset
                createObject
                createPipeline
                createPipelineTemplateVersion
                delete
                deleteDatabaseTable
                deleteObject
                downloadObject
                launchNotebookServer
                manageMembers
                update
            }
            slug
            updatedAt
        }
    }
}