query workspaces($page: Int, $perPage: Int, $pinned: Boolean, $query: String, $includeAccepted: Boolean, $page1: Int, $perPage1: Int, $page2: Int, $perPage2: Int, $page3: Int, $perPage3: Int, $query1: String){
    workspaces(page: $page3, perPage: $perPage3, query: $query1){
        items{
            bucket{
                name
            }
            connections{
                createdAt
                description
                id
                name
                slug
                type
                updatedAt
            }
            countries{
                alpha3
                code
                flag
                name
            }
            createdAt
            createdBy{
                dateJoined
                displayName
                email
                firstName
                id
                language
                lastLogin
                lastName
            }
            datasets(page: $page, perPage: $perPage, pinned: $pinned, query: $query){
                pageNumber
                totalItems
                totalPages
            }
            description
            dockerImage
            invitations(includeAccepted: $includeAccepted, page: $page1, perPage: $perPage1){
                pageNumber
                totalItems
                totalPages
            }
            members(page: $page2, perPage: $perPage2){
                pageNumber
                totalItems
                totalPages
            }
            name
            permissions{
                createConnection
                createDataset
                createObject
                createPipeline
                createPipelineTemplateVersion
                delete
                deleteDatabaseTable
                deleteObject
                downloadObject
                launchNotebookServer
                manageMembers
                update
            }
            slug
            updatedAt
        }
        pageNumber
        totalItems
        totalPages
    }
}