# Generated by ariadne-codegen
# Source: openhexa/graphql/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetWebappBySlug(BaseModel):
    webapp_by_slug: Optional["GetWebappBySlugWebappBySlug"] = Field(
        alias="webappBySlug"
    )


class GetWebappBySlugWebappBySlug(BaseModel):
    id: Any
    name: str
    description: Optional[str]
    url: str
    icon: Optional[str]
    is_favorite: bool = Field(alias="isFavorite")
    created_by: "GetWebappBySlugWebappBySlugCreatedBy" = Field(alias="createdBy")
    workspace: "GetWebappBySlugWebappBySlugWorkspace"
    permissions: "GetWebappBySlugWebappBySlugPermissions"


class GetWebappBySlugWebappBySlugCreatedBy(BaseModel):
    id: Any
    display_name: str = Field(alias="displayName")
    email: str


class GetWebappBySlugWebappBySlugWorkspace(BaseModel):
    slug: str
    name: str


class GetWebappBySlugWebappBySlugPermissions(BaseModel):
    update: bool
    delete: bool


GetWebappBySlug.model_rebuild()
GetWebappBySlugWebappBySlug.model_rebuild()
