on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.4.0
        with:
          token: ${{ secrets.RELEASE_GH_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json