name: Publish Pipelines Image on DockerHub

on: 
  workflow_dispatch:
    inputs:
      tag:
          description: 'Tag to use for the image (e.g. 1.0.0, ...)'
          required: true

jobs:
  publish:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            blsq/openhexa-pipelines
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.inputs.tag }}
            type=semver,pattern={{major}},value=${{ github.event.inputs.tag }}
            type=sha

      - name: Build and push (on release)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./docker/Dockerfile
          cache-from: type=registry,ref=blsq/openhexa-pipelines:buildcache
          cache-to: type=registry,ref=blsq/openhexa-pipelines:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}

